# Generated by Django 5.1.3 on 2025-02-08 21:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Config_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('couleur', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Image/')),
            ],
        ),
        migrations.CreateModel(
            name='EtatVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Fidelisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_code', models.TextField(help_text='Collez le code SVG ici', verbose_name='Code SVG')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='LogoPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Image/')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PieceDetache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='pieces_detachees/')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la pièce')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('prix_normal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix normal')),
                ('prix_reduit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix réduit')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Pièce détachée',
                'verbose_name_plural': 'Pièces détachées',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_code', models.TextField(help_text='Collez le code SVG ici', verbose_name='Code SVG')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hashed_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('marque', models.CharField(max_length=255)),
                ('modele', models.CharField(max_length=255)),
                ('annee', models.CharField(max_length=4)),
                ('carburant', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], max_length=50)),
                ('type', models.CharField(max_length=255)),
                ('kilometrage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('transmission', models.CharField(choices=[('manuelle', 'Manuelle'), ('auto', 'Auto')], max_length=50)),
                ('description', models.TextField()),
                ('ville', models.CharField(max_length=255)),
                ('occasion_neuve', models.CharField(help_text="Indiquez si le véhicule est neuf ou d'occasion.", max_length=255)),
                ('immatriculation', models.CharField(max_length=255, unique=True)),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('moteur', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('place', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('couleur_interieur', models.CharField(default='No Color', max_length=255)),
                ('couleur_exterieur', models.CharField(default='No Color', max_length=255)),
                ('cylindre', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('puissance_fiscale', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbre_proprio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('condition', models.CharField(max_length=255)),
                ('prix_location', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('limite_assurance', models.DateField()),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(related_name='produits', to='djona_admin.image')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='djona_admin.etatvehicule')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_nom', models.CharField(max_length=255)),
                ('client_prenom', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('duree', models.PositiveIntegerField()),
                ('date_fin', models.DateField(editable=False)),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='djona_admin.produit')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
    ]
