# Generated by Django 5.1.3 on 2025-02-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0002_clientinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_propos_de_nous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié ?')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
