# Generated by Django 5.1.3 on 2025-02-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0003_a_propos_de_nous_delete_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A_propos_de_nous',
            new_name='A_propos_de_nou',
        ),
    ]
