# Generated by Django 5.1.3 on 2025-02-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0006_nos_service_delete_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_site',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='etatvehicule',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='fidelisation',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='information',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='logopartenaire',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='piecedetache',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='produit',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='valeur',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
    ]
