# Generated by Django 5.1.3 on 2025-02-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0007_config_site_is_published_etatvehicule_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Adapte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_code', models.TextField(help_text='Collez le code SVG ici', verbose_name='Code SVG')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
